"""Supabase database query modules."""
from backend.database.supabase import (
    create_cover_letter,
    create_cv,
    create_profile,
    delete_cover_letter,
    delete_cv,
    delete_profile,
    delete_profile_by_updated_at,
    get_cover_letter_by_id,
    get_cv_by_filename,
    get_cv_by_id,
    get_profile,
    get_profile_by_updated_at,
    list_cover_letters,
    list_cvs,
    list_profiles,
    save_profile,
    search_cvs,
    set_cv_filename,
    update_cv,
    update_profile,
)

__all__ = [
    "create_cv",
    "create_cover_letter",
    "get_cv_by_id",
    "get_cv_by_filename",
    "get_cover_letter_by_id",
    "list_cvs",
    "search_cvs",
    "list_cover_letters",
    "update_cv",
    "set_cv_filename",
    "delete_cv",
    "delete_cover_letter",
    "save_profile",
    "create_profile",
    "update_profile",
    "get_profile",
    "delete_profile",
    "delete_profile_by_updated_at",
    "list_profiles",
    "get_profile_by_updated_at",
]
